services:
  db:
    build:
      context: ./db
    hostname: db
    command:
      - --ssl=on
      - --ssl_cert_file=/var/lib/postgresql/certs/db.crt
      - --ssl_key_file=/var/lib/postgresql/certs/db.key
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 5s
  ldap:
    build:
      context: ./ldap
    hostname: ldap
    expose:
      - 389
      - 636
    environment:
      LDAP_ORGANISATION: Homelab
      LDAP_DOMAIN: home.lab
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_TLS: true
      LDAP_TLS_CRT_FILENAME: ldap.crt
      LDAP_TLS_KEY_FILENAME: ldap.key
      LDAP_TLS_CA_CRT_FILENAME: ca.crt
      LDAP_TLS_VERIFY_CLIENT: try
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-conf:/etc/ldap/slapd.d
  ldap-admin:
    build:
      context: ./ldap-admin
    hostname: ldap-admin
    ports:
      - 127.0.0.1:5443:443
    environment:
      PHPLDAPADMIN_HTTPS: true
      PHPLDAPADMIN_HTTPS_CRT_FILENAME: ldap-admin.crt
      PHPLDAPADMIN_HTTPS_KEY_FILENAME: ldap-admin.key
      PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME: ca.crt
      PHPLDAPADMIN_LDAP_CLIENT_TLS: true
      PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: demand
      PHPLDAPADMIN_LDAP_CLIENT_TLS_CA_CRT_FILENAME: ca.crt
      PHPLDAPADMIN_LDAP_CLIENT_TLS_CRT_FILENAME: ldap-client.crt
      PHPLDAPADMIN_LDAP_CLIENT_TLS_KEY_FILENAME: ldap-client.key
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldap': [{'server': [{'tls': True}]}]}]"
    depends_on:
      ldap:
        condition: service_started
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    hostname: keycloak
    ports:
      - ${HOST_IP}:6443:6443
    command:
      - start
      - --https-certificate-file=/run/secrets/keycloak.crt
      - --https-certificate-key-file=/run/secrets/keycloak.key
      - --hostname=${HOST_IP}
      - --hostname-strict-backchannel=true
      - --https-port=6443
      - --spi-truststore-file-file=/run/secrets/truststore.jks
      - --spi-truststore-file-password=${KEYCLOAK_TRUSTSTORE_PASSWORD}
      - --spi-truststore-file-hostname-verification-policy=WILDCARD
      - --spi-truststore-file-type=pkcs12
      - --db=postgres
      - --db-url-host=db
      - --db-url-port=5432
      - --db-url-database=keycloak
      - --db-url-properties=?ssl,sslmode=verify-full,sslcert=/run/secrets/ca.crt
      - --db-username=${POSTGRES_USER}
      - --db-password=${POSTGRES_PASSWORD}
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    secrets:
      - keycloak.crt
      - keycloak.key
      - truststore.jks
      - ca.crt
    depends_on:
      ldap:
        condition: service_started
      db:
        condition: service_healthy

  gitea:
    build:
      context: ./gitea
    hostname: gitea
    environment:
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: db:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: ${POSTGRES_USER}
      GITEA__database__PASSWD: ${POSTGRES_PASSWORD}
      GITEA__database__SSL_MODE: verify-full
      GITEA__server__CERT_FILE: gitea.crt
      GITEA__server__KEY_FILE: gitea.key
      GITEA__server__PROTOCOL: https
      GITEA__server__DOMAIN: ${HOST_IP}
      GITEA__server__HTTP_PORT: 3443
      GITEA__server__ROOT_URL: https://${HOST_IP}:3443
      GITEA__service__DISABLE_REGISTRATION: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - gitea:/data
    ports:
      - ${HOST_IP}:3443:3443
      - 127.0.0.1:2222:22
    depends_on:
      db:
        condition: service_healthy
      ldap:
        condition: service_started

volumes:
  pgdata:
  ldap-data:
  ldap-conf:
  gitea:

secrets:
  keycloak.crt:
    file: ./secrets/keycloak/keycloak.crt
  keycloak.key:
    file: ./secrets/keycloak/keycloak.key
  truststore.jks:
    file: ./secrets/keycloak/truststore.jks
  ca.crt:
    file: ./secrets/keycloak/ca.crt
